baseurl = "https://emil.lerch.org"
languageCode = "en-us"
title = "Emil Lerch"
SectionPagesMenu = "main"
pygmentsStyle = "monokai"
pygmentsCodefences = true
pygmentsUseClasses = false
theme = "gindoro"
relativeURLs = true

[author]
    name = "Emil Lerch"

[permalinks]
    posts = "/:slug/"

[params]
    Author = "Emil Lerch"
    Copyright = "<a href='http://creativecommons.org/licenses/by/4.0/' title='Creative Commons Attribution'>Creative Commons Attribution-ShareAlike 4.0 International License</a>. Please attribute properly and link back."
    Description = "Husband, Father, Technologist, Cloud Architect"
    GitHubUser = "elerch"
    TwitterUser = "elerch"
    LinkedInUser = "emillerch"
    MastodonUser = "@emil"
    MastodonInstance = "mstdn.io"
    disqusShortname = "emillerch"

[markup]
    [markup.highlight]
        noclasses = true

[blackfriday]
    smartypants = false
    angledQuotes = false
    smartDashes = false
    latexDashes = false
