#!/bin/sh
# by taking "created" off, we can easily enable
# vi $(./new_post yada-yada) and enter an editor
if [ $# -ne 1 ]; then
  echo "usage: $0 <post-name>"
  echo 'suggestion: vi $(./new-post <post-name>)'
  echo "you likely also want to run nix develop first (or otherwise ensure hugo exists)"
  return 0
fi
command -v "hugo" > /dev/null 2>&1
hugo_exists=$?
if [ $hugo_exists -ne 0 ]; then
  echo 'Hugo does not exist as a command - please run "nix develop" and re-run' >&2
  return 1
fi

git switch -c "$1"
rc=$?
if [ ! $rc ]; then
  echo 'could not switch branches'
  return $rc
fi
filename=$(hugo new "posts/$(date +%Y-%m-%d)/$1.md" |cut -f 2 -d ' '|tr -d \")
rc=$?
# HUGO - WTF! YOU REPORT SUCCESSFUL EXIT CODE ON ERROR!!!!!!!
if [ -z "$filename" ]; then
  echo Could not create new post
  return 1 #$rc
fi
echo "---
title: \"$1\"
date: $(date -Iseconds)
draft: false
---

$1
==
" > "$filename"

echo "$filename"
